"""Generate both clients from the reviewed, source-linked park guidance."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent

def build():
    parks = json.loads((ROOT / 'data/park-guidance.json').read_text())
    assert len(parks) == 63
    summary = {}
    for id, p in parks.items():
        assert id == p['id'] and p['sources'] and p['description'] and p['planningNote']
        assert all(1 <= m <= 12 for m in p['bestMonths'])
        summary[id] = {k: p[k] for k in ['id', 'name', 'state', 'bestMonths', 'minDays', 'thumbnail']}
        summary[id]['cardThumbnail'] = f'assets/images/parks/cards/{id}.jpg'
        summary[id].update(topActivity=p['activities'][0], stargazing=p['nightSkyListed'], recommendation=p['recommendation'], photo=p['photo'])
    def js(path, name, data):
        (ROOT / path).write_text('// Generated by scripts/build_park_data.py. Edit data/park-guidance.json.\nwindow.' + name + ' = ' + json.dumps(data, ensure_ascii=False, indent=2) + ';\n')
    js('data/parks-summary.js', 'PARKS_SUMMARY', summary)
    (ROOT / 'data/parks-summary.json').write_text(json.dumps(summary, ensure_ascii=False, indent=2)+'\n')
    js('data/parks-details.js', 'PARKS_DETAILS', parks)
    # Keep old URLs safe for cached clients; never regenerate unsupported observations.
    js('data/parks-seasonal.js', 'PARKS_SEASONAL', {})
    js('data/parks-logistics.js', 'PARKS_LOGISTICS', {})
    (ROOT / 'data.js').write_text('// Retired legacy dataset. Load data/parks-summary.js and data/parks-details.js instead.\nwindow.PARKS_DATA = [];\n')

if __name__ == '__main__':
    build()
